owner: TeamPiped
repo: piped-uptime
sites: []
status-website:
  cname: status.piped.video
  introMessage: A status page for Piped instances, with uptime and **INACCURATE**
    response time information.
  introTitle: Piped Instances status
  logoUrl: https://raw.githubusercontent.com/uppthttps://cdn.jsdelivr.net/gh/TeamPiped/Piped@fcea986/public/img/icons/logo.svgime/upptime.js.org/master/static/img/icon.svg
  name: Piped Instances Status
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
