owner: TeamPiped
repo: piped-uptime
sites:
- name: kavin.rocks (Official)
  url: https://pipedapi.kavin.rocks/healthcheck
- name: tokhmi.xyz
  url: https://pipedapi.tokhmi.xyz/healthcheck
- name: moomoo.me
  url: https://pipedapi.moomoo.me/healthcheck
- name: syncpundit.io
  url: https://pipedapi.syncpundit.io/healthcheck
- name: mha.fi
  url: https://api-piped.mha.fi/healthcheck
- name: whatever.social
  url: https://watchapi.whatever.social/healthcheck
- name: garudalinux.org
  url: https://piped-api.garudalinux.org/healthcheck
- name: rivo.lol
  url: https://pipedapi.rivo.lol/healthcheck
- name: aeong.one
  url: https://pipedapi.aeong.one/healthcheck
- name: leptons.xyz
  url: https://pipedapi.leptons.xyz/healthcheck
- name: lunar.icu
  url: https://piped-api.lunar.icu/healthcheck
- name: kavin.rocks libre (Official)
  url: https://pipedapi-libre.kavin.rocks/healthcheck
- name: jae.fi
  url: https://api.yt.jae.fi/healthcheck
- name: mint.lgbt
  url: https://pa.mint.lgbt/healthcheck
- name: il.ax
  url: https://pa.il.ax/healthcheck
- name: privacy.com.de
  url: https://piped-api.privacy.com.de/healthcheck
- name: esmailelbob.xyz
  url: https://pipedapi.esmailelbob.xyz/healthcheck
- name: projectsegfau.lt
  url: https://api.piped.projectsegfau.lt/healthcheck
- name: privacydev.net
  url: https://api.piped.privacydev.net/healthcheck
- name: palveluntarjoaja.eu
  url: https://pipedapi.palveluntarjoaja.eu/healthcheck
- name: plibre.com
  url: https://p.plibre.com/healthcheck
- name: smnz.de
  url: https://pipedapi.smnz.de/healthcheck
- name: adminforge.de
  url: https://pipedapi.adminforge.de/healthcheck
- name: qdi.fi
  url: https://pipedapi.qdi.fi/healthcheck
- name: hostux.net
  url: https://piped-api.hostux.net/healthcheck
- name: vern.cc
  url: https://pdapi.vern.cc/healthcheck
- name: chauvet.pro
  url: https://pipedapi.chauvet.pro/healthcheck
- name: berryez.xyz
  url: https://pipedapi.berryez.xyz/healthcheck
status-website:
  cname: status.piped.video
  introMessage: A status page for Piped instances, with uptime and **INACCURATE**
    response time information.
  introTitle: Piped Instances status
  logoUrl: https://raw.githubusercontent.com/uppthttps://cdn.jsdelivr.net/gh/TeamPiped/Piped@fcea986/public/img/icons/logo.svgime/upptime.js.org/master/static/img/icon.svg
  name: Piped Instances Status
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
