owner: TeamPiped
repo: piped-uptime
sites:
- name: kavin.rocks (Official)
  url: https://pipedapi.kavin.rocks/healthcheck
- name: tokhmi.xyz
  url: https://pipedapi.tokhmi.xyz/healthcheck
- name: moomoo.me
  url: https://pipedapi.moomoo.me/healthcheck
- name: syncpundit.io
  url: https://pipedapi.syncpundit.io/healthcheck
- name: mha.fi
  url: https://api-piped.mha.fi/healthcheck
- name: garudalinux.org
  url: https://piped-api.garudalinux.org/healthcheck
- name: rivo.lol
  url: https://pipedapi.rivo.lol/healthcheck
- name: aeong.one
  url: https://pipedapi.aeong.one/healthcheck
- name: leptons.xyz
  url: https://pipedapi.leptons.xyz/healthcheck
- name: lunar.icu
  url: https://piped-api.lunar.icu/healthcheck
- name: dc09.ru
  url: https://ytapi.dc09.ru/healthcheck
- name: colinslegacy.com
  url: https://pipedapi.colinslegacy.com/healthcheck
- name: vyper.me
  url: https://yapi.vyper.me/healthcheck
- name: looleh.xyz
  url: https://api.looleh.xyz/healthcheck
- name: kavin.rocks libre (Official)
  url: https://pipedapi-libre.kavin.rocks/healthcheck
- name: mint.lgbt
  url: https://pa.mint.lgbt/healthcheck
- name: il.ax
  url: https://pa.il.ax/healthcheck
- name: privacy.com.de
  url: https://piped-api.privacy.com.de/healthcheck
- name: projectsegfau.lt
  url: https://api.piped.projectsegfau.lt/healthcheck
- name: projectsegfau.lt in
  url: https://pipedapi.in.projectsegfau.lt/healthcheck
- name: projectsegfau.lt us
  url: https://pipedapi.us.projectsegfau.lt/healthcheck
- name: whatever.social
  url: https://watchapi.whatever.social/healthcheck
- name: privacydev.net
  url: https://api.piped.privacydev.net/healthcheck
- name: palveluntarjoaja.eu
  url: https://pipedapi.palveluntarjoaja.eu/healthcheck
- name: smnz.de
  url: https://pipedapi.smnz.de/healthcheck
- name: adminforge.de
  url: https://pipedapi.adminforge.de/healthcheck
- name: qdi.fi
  url: https://pipedapi.qdi.fi/healthcheck
- name: hostux.net
  url: https://piped-api.hostux.net/healthcheck
- name: vern.cc
  url: https://pdapi.vern.cc/healthcheck
- name: pfcd.me
  url: https://pipedapi.pfcd.me/healthcheck
- name: frontendfriendly.xyz
  url: https://pipedapi.frontendfriendly.xyz/healthcheck
- name: piped.yt
  url: https://api.piped.yt/healthcheck
- name: astartes.nl
  url: https://pipedapi.astartes.nl/healthcheck
- name: osphost.fi
  url: https://pipedapi.osphost.fi/healthcheck
- name: simpleprivacy.fr
  url: https://pipedapi.simpleprivacy.fr/healthcheck
- name: drgns.space
  url: https://pipedapi.drgns.space/healthcheck
- name: ggtyler.dev
  url: https://piapi.ggtyler.dev/healthcheck
- name: pluto.lat
  url: https://api.watch.pluto.lat/healthcheck
status-website:
  cname: status.piped.video
  introMessage: A status page for Piped instances, with uptime and **INACCURATE**
    response time information.
  introTitle: Piped Instances status
  logoUrl: https://raw.githubusercontent.com/uppthttps://cdn.jsdelivr.net/gh/TeamPiped/Piped@fcea986/public/img/icons/logo.svgime/upptime.js.org/master/static/img/icon.svg
  name: Piped Instances Status
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
